services:
  backend:
    build: .
    container_name: homi-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: homi-db
    restart: always
    environment:
      POSTGRES_USER: homiuser
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: homidb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U homiuser -d homidb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  uploads: