export const AMENITIES_SEED = [
  // =========================
  // COMMON ACCESS
  // =========================
  {
    nameEn: 'Road access',
    nameMl: 'റോഡ് പ്രവേശനം',
    iconName: 'road',
    isLand: true,
    isHouse: true,
    isBuilding: true,
    isHotel: true,
    sortOrder: 1,
  },
  {
    nameEn: 'Electricity available',
    nameMl: 'വൈദ്യുതി സൗകര്യം',
    iconName: 'flash',
    isLand: true,
    isHouse: true,
    isBuilding: true,
    isHotel: true,
    sortOrder: 2,
  },
  {
    nameEn: 'Water connection',
    nameMl: 'ജല കണക്ഷൻ',
    iconName: 'water',
    isLand: true,
    isHouse: true,
    isBuilding: true,
    isHotel: true,
    sortOrder: 3,
  },
  {
    nameEn: 'Well water',
    nameMl: 'കിണർ വെള്ളം',
    iconName: 'water-well',
    isLand: true,
    isHouse: true,
    isBuilding: false,
    isHotel: false,
    sortOrder: 4,
  },

  // =========================
  // LOCATION / NEARBY
  // =========================
  {
    nameEn: 'Bus stop nearby',
    nameMl: 'ബസ് സ്റ്റോപ്പ് സമീപം',
    iconName: 'bus-stop',
    isLand: true,
    isHouse: true,
    isBuilding: true,
    isHotel: true,
    sortOrder: 10,
  },
  {
    nameEn: 'School nearby',
    nameMl: 'സ്കൂൾ സമീപം',
    iconName: 'school',
    isLand: true,
    isHouse: true,
    isBuilding: true,
    isHotel: true,
    sortOrder: 11,
  },
  {
    nameEn: 'Hospital nearby',
    nameMl: 'ആശുപത്രി സമീപം',
    iconName: 'hospital',
    isLand: true,
    isHouse: true,
    isBuilding: true,
    isHotel: true,
    sortOrder: 12,
  },
  {
    nameEn: 'Market nearby',
    nameMl: 'മാർക്കറ്റ് സമീപം',
    iconName: 'shopping',
    isLand: true,
    isHouse: true,
    isBuilding: true,
    isHotel: true,
    sortOrder: 13,
  },
  {
    nameEn: 'Highway access',
    nameMl: 'ഹൈവേ പ്രവേശനം',
    iconName: 'highway',
    isLand: true,
    isHouse: false,
    isBuilding: true,
    isHotel: true,
    sortOrder: 14,
  },

  // =========================
  // LAND SPECIFIC
  // =========================
  {
    nameEn: 'Boundary wall',
    nameMl: 'ബൗണ്ടറി മതിൽ',
    iconName: 'wall',
    isLand: true,
    isHouse: false,
    isBuilding: false,
    isHotel: false,
    sortOrder: 20,
  },
  {
    nameEn: 'Gated property',
    nameMl: 'ഗേറ്റുള്ള സ്ഥലം',
    iconName: 'gate',
    isLand: true,
    isHouse: false,
    isBuilding: false,
    isHotel: false,
    sortOrder: 21,
  },
  {
    nameEn: 'Coconut trees',
    nameMl: 'തെങ്ങുകൾ',
    iconName: 'palm-tree',
    isLand: true,
    isHouse: false,
    isBuilding: false,
    isHotel: false,
    sortOrder: 22,
  },

  // =========================
  // HOUSE
  // =========================
  {
    nameEn: 'Parking space',
    nameMl: 'പാർക്കിംഗ് സൗകര്യം',
    iconName: 'parking',
    isLand: false,
    isHouse: true,
    isBuilding: true,
    isHotel: true,
    sortOrder: 30,
  },
  {
    nameEn: 'Balcony',
    nameMl: 'ബാൽക്കണി',
    iconName: 'balcony',
    isLand: false,
    isHouse: true,
    isBuilding: true,
    isHotel: true,
    sortOrder: 32,
  },
  {
    nameEn: 'Garden',
    nameMl: 'തോട്ടം',
    iconName: 'flower',
    isLand: false,
    isHouse: true,
    isBuilding: false,
    isHotel: false,
    sortOrder: 33,
  },
  {
    nameEn: 'Solar power',
    nameMl: 'സോളാർ വൈദ്യുതി',
    iconName: 'solar-power',
    isLand: false,
    isHouse: true,
    isBuilding: true,
    isHotel: false,
    sortOrder: 34,
  },

  // =========================
  // BUILDING / COMMERCIAL
  // =========================
  {
    nameEn: 'Lift facility',
    nameMl: 'ലിഫ്റ്റ് സൗകര്യം',
    iconName: 'elevator-passenger',
    isLand: false,
    isHouse: false,
    isBuilding: true,
    isHotel: true,
    sortOrder: 40,
  },
  {
    nameEn: 'Security',
    nameMl: 'സുരക്ഷാ സംവിധാനം',
    iconName: 'human-male',
    isLand: false,
    isHouse: false,
    isBuilding: true,
    isHotel: true,
    sortOrder: 41,
  },
  {
    nameEn: 'CCTV',
    nameMl: 'സിസിടിവി',
    iconName: 'cctv',
    isLand: false,
    isHouse: false,
    isBuilding: true,
    isHotel: true,
    sortOrder: 42,
  },
  {
    nameEn: 'Power backup',
    nameMl: 'പവർ ബാക്കപ്പ്',
    iconName: 'generator-portable',
    isLand: false,
    isHouse: false,
    isBuilding: true,
    isHotel: true,
    sortOrder: 43,
  },

  // =========================
  // HOTEL / PG
  // =========================
  {
    nameEn: 'Wi-Fi',
    nameMl: 'വൈഫൈ',
    iconName: 'wifi',
    isLand: false,
    isHouse: false,
    isBuilding: false,
    isHotel: true,
    sortOrder: 50,
  },
  {
    nameEn: 'AC rooms',
    nameMl: 'എസി മുറികൾ',
    iconName: 'air-conditioner',
    isLand: false,
    isHouse: false,
    isBuilding: false,
    isHotel: true,
    sortOrder: 51,
  },
  {
    nameEn: 'Food included',
    nameMl: 'ഭക്ഷണം ഉൾപ്പെടുന്നു',
    iconName: 'food',
    isLand: false,
    isHouse: false,
    isBuilding: false,
    isHotel: true,
    sortOrder: 52,
  },
  {
    nameEn: 'Laundry service',
    nameMl: 'ലോണ്ട്രി സേവനം',
    iconName: 'washing-machine',
    isLand: false,
    isHouse: false,
    isBuilding: false,
    isHotel: true,
    sortOrder: 53,
  },
  {
    nameEn: '24x7 reception',
    nameMl: '24 മണിക്കൂർ റിസപ്ഷൻ',
    iconName: 'desk',
    isLand: false,
    isHouse: false,
    isBuilding: false,
    isHotel: true,
    sortOrder: 54,
  },
] as const;